"""initial schema

Revision ID: d135a14ecda2
Revises: 
Create Date: 2026-05-30 02:55:49.358200
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import server.db.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = 'd135a14ecda2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log',
    sa.Column('log_id', server.db.types.GUID(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('accessor_id', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('resource', sa.String(length=128), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_access_log'))
    )
    op.create_index(op.f('ix_access_log_occurred_at'), 'access_log', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_access_log_user_id'), 'access_log', ['user_id'], unique=False)
    op.create_table('biomarker_readings',
    sa.Column('reading_id', server.db.types.GUID(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('crp', sa.Float(), nullable=True),
    sa.Column('esr', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('reading_id', name=op.f('pk_biomarker_readings'))
    )
    op.create_index(op.f('ix_biomarker_readings_user_id'), 'biomarker_readings', ['user_id'], unique=False)
    op.create_table('bucket_reports',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('bucket_id', sa.String(length=128), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence_level', sa.String(length=16), nullable=False),
    sa.Column('overall_quality', sa.Float(), nullable=False),
    sa.Column('flare_probability', sa.Float(), nullable=True),
    sa.Column('severity_composite', sa.Float(), nullable=True),
    sa.Column('severity_band', sa.String(length=16), nullable=True),
    sa.Column('matched_patterns', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('decision', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('explanation', server.db.types.EncryptedString(length=4000), nullable=True),
    sa.Column('calibration_version', sa.String(length=16), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'bucket_id', name=op.f('pk_bucket_reports'))
    )
    op.create_table('calibration_lr',
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('lr_positive', sa.Float(), nullable=False),
    sa.Column('lr_negative', sa.Float(), nullable=False),
    sa.Column('signal_threshold', sa.Float(), nullable=False),
    sa.Column('low_threshold', sa.Float(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('version', 'agent_id', name=op.f('pk_calibration_lr'))
    )
    op.create_table('consents',
    sa.Column('consent_id', server.db.types.GUID(), nullable=False),
    sa.Column('user_id', server.db.types.GUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=64), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('consent_id', name=op.f('pk_consents'))
    )
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_table('corroboration_patterns',
    sa.Column('pattern_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_agents', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('optional_agents', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('pattern_id', name=op.f('pk_corroboration_patterns'))
    )
    op.create_table('delete_log',
    sa.Column('delete_id', server.db.types.GUID(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=128), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('delete_id', name=op.f('pk_delete_log'))
    )
    op.create_index(op.f('ix_delete_log_user_id'), 'delete_log', ['user_id'], unique=False)
    op.create_table('dietary_logs',
    sa.Column('log_id', server.db.types.GUID(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('bucket_id', sa.String(length=128), nullable=False),
    sa.Column('meal_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('description', server.db.types.EncryptedString(length=2000), nullable=True),
    sa.Column('photo_id', server.db.types.GUID(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_dietary_logs'))
    )
    op.create_index(op.f('ix_dietary_logs_bucket_id'), 'dietary_logs', ['bucket_id'], unique=False)
    op.create_index(op.f('ix_dietary_logs_user_id'), 'dietary_logs', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bucket_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_bucket_id'), 'events', ['bucket_id'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('flare_button_events',
    sa.Column('event_id', server.db.types.GUID(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('pressed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('bucket_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_flare_button_events'))
    )
    op.create_index(op.f('ix_flare_button_events_user_id'), 'flare_button_events', ['user_id'], unique=False)
    op.create_table('knowledge_entries',
    sa.Column('entry_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('diseases', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('entry_id', name=op.f('pk_knowledge_entries'))
    )
    op.create_table('photos',
    sa.Column('photo_id', server.db.types.GUID(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('bucket_id', sa.String(length=128), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('user_description', server.db.types.EncryptedString(length=2000), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('photo_id', name=op.f('pk_photos'))
    )
    op.create_index(op.f('ix_photos_user_id'), 'photos', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', server.db.types.GUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('disease', sa.String(length=64), nullable=True),
    sa.Column('date_of_birth', server.db.types.EncryptedString(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_profiles'))
    )
    op.create_table('symptom_logs',
    sa.Column('log_id', server.db.types.GUID(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('bucket_id', sa.String(length=128), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('fatigue', sa.Float(), nullable=True),
    sa.Column('joint_pain', sa.Float(), nullable=True),
    sa.Column('brain_fog_severity', sa.Float(), nullable=True),
    sa.Column('gi_distress', sa.Float(), nullable=True),
    sa.Column('skin_severity', sa.Float(), nullable=True),
    sa.Column('sleep_severity', sa.Float(), nullable=True),
    sa.Column('energy_severity', sa.Float(), nullable=True),
    sa.Column('wellness_severity', sa.Float(), nullable=True),
    sa.Column('phq8_score', sa.Float(), nullable=True),
    sa.Column('gad7_score', sa.Float(), nullable=True),
    sa.Column('free_text', server.db.types.EncryptedString(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_symptom_logs'))
    )
    op.create_index(op.f('ix_symptom_logs_bucket_id'), 'symptom_logs', ['bucket_id'], unique=False)
    op.create_index(op.f('ix_symptom_logs_user_id'), 'symptom_logs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', server.db.types.GUID(), nullable=False),
    sa.Column('email', server.db.types.EncryptedString(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('wearable_readings',
    sa.Column('reading_id', server.db.types.GUID(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('night_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hrv_rmssd', sa.Float(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('reading_id', name=op.f('pk_wearable_readings'))
    )
    op.create_index(op.f('ix_wearable_readings_user_id'), 'wearable_readings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wearable_readings_user_id'), table_name='wearable_readings')
    op.drop_table('wearable_readings')
    op.drop_table('users')
    op.drop_index(op.f('ix_symptom_logs_user_id'), table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_bucket_id'), table_name='symptom_logs')
    op.drop_table('symptom_logs')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_photos_user_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_table('knowledge_entries')
    op.drop_index(op.f('ix_flare_button_events_user_id'), table_name='flare_button_events')
    op.drop_table('flare_button_events')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_bucket_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_dietary_logs_user_id'), table_name='dietary_logs')
    op.drop_index(op.f('ix_dietary_logs_bucket_id'), table_name='dietary_logs')
    op.drop_table('dietary_logs')
    op.drop_index(op.f('ix_delete_log_user_id'), table_name='delete_log')
    op.drop_table('delete_log')
    op.drop_table('corroboration_patterns')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_table('calibration_lr')
    op.drop_table('bucket_reports')
    op.drop_index(op.f('ix_biomarker_readings_user_id'), table_name='biomarker_readings')
    op.drop_table('biomarker_readings')
    op.drop_index(op.f('ix_access_log_user_id'), table_name='access_log')
    op.drop_index(op.f('ix_access_log_occurred_at'), table_name='access_log')
    op.drop_table('access_log')
    # ### end Alembic commands ###
